---
language: go

go:
  - 1.5
  - 1.5.3
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip

sudo : false

script:
  - if [ "$TRAVIS_REPO_SLUG" != "fluffle/goirc" ] ; then ln -s "$HOME/gopath/src/github.com/$TRAVIS_REPO_SLUG" /home/travis/gopath/src/github.com/lfkeitel/goirc ; fi
  - go test -v ./...
